name: 'gradle dependency-analysis reviewdog hook'
description: | 
  Provides a @reviewdog/reviewdog check for @autonomousapps/dependency-analysis-gradle-plugin
author: 'Kevin Brightwell'
branding:
  icon: check-circle
  color: green

# Define your inputs here.
inputs:
  reviewdog-github-token:
    description: Github Token for posting checks/comments
    required: true

  build-report-path:
    description: 'Path to the build report'
    required: true
    default: build/reports/dependency-analysis/build-health-report.txt

  reviewdog-reporter:
    description: 'reviewdog reporter to use, default: `github-pr-check`'
    required: true
    default: github-pr-check
  reviewdog-check-name:
    description: 'reviewdog name to use, default: `buildHealth`'
    required: true
    default: buildHealth

  gradle-root:
    description: 'Root directory of the gradle project'
    required: true
    default: .

runs:
  using: "composite"
  steps:
    - name: File Existence
      uses: andstor/file-existence-action@v3
      id: report_exists
      with:
        files: ${{ inputs.build-report-path }}

    - uses: reviewdog/action-setup@v1
      if: ${{ steps.report_exists.outputs.files_exists == 'true' }}
      with:
        reviewdog_version: latest

    - uses: actions/setup-python@v5
      if: ${{ steps.report_exists.outputs.files_exists == 'true' }}
      with:
        python-version: '3.12.1'

    - shell: bash
      name: Run reviewdog 🐶
      if: ${{ steps.report_exists.outputs.files_exists == 'true' }}
      run: |
        python "${{ github.action_path }}/build_health_parser/parse_build_health_report.py" \
               --gradle_root="${{ inputs.gradle-root }}" \
               "${{ inputs.build-report-path }}" | \
            reviewdog -name="${{ inputs.reviewdog-check-name }}" \
                      -reporter="${{ inputs.reviewdog-reporter }}" \
                      -efm="%f:%l:%c: %m" \
                      -filter-mode=nofilter
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.reviewdog-github-token }}

