name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-python:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  run-action:
    name: Run Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Run action
        uses: ./
        with:
          reviewdog-github-token: ${{ secrets.GITHUB_TOKEN }}
          build-report-path: ./functional_test/build-health-report.txt
          gradle-root: ./functional_test

          # Don't try and post content to GitHub
          reviewdog-reporter: local
